### ISSUE TITLE
SVG gradients don't render with hash urls

### ISSUE THREAD

**Issue by statianzo** [DmitryBaranovskiy/raphael#933]
Browser:  Chromium 39.0.2171.95 and Firefox 35.0
OS: Arch Linux

If your browser is at `http://example.com/people#xyz` and on that page you render a rectangle with a fill of `90-#FFF-#000`, then the fill attribute of the rect is set to `url(http://example.com/people/#xyz#90-_FFF-_000)`. The fill won't show because it's attempting to locate the lineargradient with an id of `#xyz#90-_FFF-_000` rather than the expected `#90-_FFF-_000`.

The issue stems from https://github.com/DmitryBaranovskiy/raphael/blob/master/dev/raphael.svg.js#L130 where `document.location` is not filtering out existing hashes.

My use case is an Angular application that uses hash routing.

**Comment by tomasAlabes** [comment]
Fixed with 0dfdb6f253932923f8e4089ee7a4b10d60e0594f, could you confirm it? Thanks

**Comment by andreatevoi** [comment]
Hi,

still have the same issue even with that fix.
Shouldn't avoid to append "document.location.origin + document.location.pathname" to gradient URL?
Without that it seems to work fine.

Cheers,
Andrea
